baseURL = "http://paksyy.github.io/grayape/"
languageCode = "en-us"
title = "grayape"
theme = "hello-friend-ng"

[params]
  defaultTheme = "dark"
  enableThemeToggle = true
  homeTitle = "grayape login"
  customCSS = ["css/custom.css"]
  relativeURLs = true
  canonifyURLs = true

[params.Portrait]
  Path = "images/avatar.png"
  Alt = "My avatar"
  MaxWidth = "150px"

[[params.social]]
name = "github"
url = "https://github.com/paksyy"

[[params.social]]
name = "email"
url = "mailto:grayaperm@gmail.com"

[menu]
  [[menu.main]]
    name = "projects"
    url = "/projects/"
    weight = 1

  [[menu.main]]
    name = "learningPath"
    url = "/learningPath/"
    weight = 2

  [[menu.main]]
    name = "hacklog"
    url = "/hacklog/"
    weight = 3

